# Generated by Django 5.0.3 on 2025-11-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
