# Generated by Django 5.0.3 on 2025-11-15 13:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_report_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-date_created"]},
        ),
        migrations.RenameField(
            model_name="report",
            old_name="contact",
            new_name="number",
        ),
        migrations.AlterField(
            model_name="report",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
