# Generated by Django 5.2.6 on 2025-10-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="humidity",
        ),
        migrations.RemoveField(
            model_name="station",
            name="rain_chance",
        ),
        migrations.RemoveField(
            model_name="station",
            name="temperature",
        ),
    ]
