# Generated by Django 5.2.6 on 2025-09-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="location_name",
            field=models.CharField(default="CMU Campus", max_length=100),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
