# Generated by Django 5.2.6 on 2025-09-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customuser_username_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
